# FROM locusview/github-common/common/.github/workflows/call_pr_title.yml

name: PR title check

# Controls when the action will run.
on:

  pull_request:
    types: [opened, edited, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  github-common:
    uses: locusview/github-common/.github/workflows/pr_title.yml@master
